[package]
name = "mylang"
version = "0.1.0"
authors = ["Jonathan B Coe <jonathanbcoe@gmail.com>"]
edition = "2018"

[[bin]]
name = "lexer"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
